Repository vitejs/awesome-vite, pull requests merged in 2021-05, with the labels that each got.

#147 docs: add wp2vite
  README.md
Labels: change request

#151 feat: add apps
  README.md
Labels: queue

#168 Add fast-crud
  README.md
Labels: change requested

#153 Add admin-base-tmpl
  README.md
Labels: change requested

#150 feat: vivu
  README.md
Labels: change requested

#165 feat: add vite-plugin-cdn-import
  README.md
Labels: change requested
